name = "rapidtools-monitoring"
main = "src/index.ts"
compatibility_date = "2024-12-18"

# Run every 10 minutes
[triggers]
crons = ["*/10 * * * *"]

# Environment variables for alert email
[vars]
ALERT_EMAIL = "security@rapidtools.dev"
ALERT_FROM = "monitoring@rapidtools.dev"
